theme: jekyll-theme-minimal
title: CIT 281 - Lab 3
description: I learned to refactor JavaScript code to modern syntax, destructure an object, convert normal functions into arrow functions, examine using for..in  syntax with objects, practice using for..of syntax with arrays, create a Node.js compatible code module using module.exports, import a Node.js compatible code module using require, and examine code using the spread operator. 


